name: License Manager CI/CD

on:
  push:
    branches:
      - main
      - license-feature
      - license-testcase
      - cicd-implementation
      - usermanagement
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22]

    environment: MONGO_URI

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Print Env Secret
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
        run: |
          echo "Secret 1 is set"
          echo "Secret 2 is set"
          echo "Secret 3 is set"

      - name: Stop Running Services
        run: |
          /home/ubuntu/.nvm/versions/node/v22.22.2/bin/pm2 stop all || true

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: |
          npm install --global yarn
          yarn --version
          yarn install

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: |
          df -h
          sudo rm -rf ./build
          yarn install

      - name: Build Frontend
        working-directory: ./frontend
        run: yarn run build

      - name: Run Backend Tests
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
        working-directory: ./backend
        run: npm test

      - name: Run npm ci
        run: npm ci

      - name: Create Backend .env File
        run: |
          cd backend
          cat > .env <<EOF
          MONGO_URI=${{ secrets.MONGO_URI }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          PORT=${{ secrets.PORT }}
          EOF

      - name: Free Ports Safely
        run: |
          if lsof -i:5001 -t > /dev/null; then
            echo "Port 5001 in use. Killing..."
            sudo fuser -k 5001/tcp
          else
            echo "Port 5001 is free"
          fi

          if lsof -i:3000 -t > /dev/null; then
            echo "Port 3000 in use. Killing..."
            sudo fuser -k 3000/tcp
          else
            echo "Port 3000 is free"
          fi

      - name: Restart Backend with PM2
        run: |
          /home/ubuntu/.nvm/versions/node/v22.22.2/bin/pm2 delete license-backend || true
          cd backend
          /home/ubuntu/.nvm/versions/node/v22.22.2/bin/pm2 start server.js --name license-backend
          /home/ubuntu/.nvm/versions/node/v22.22.2/bin/pm2 status

      - name: Restart Frontend with PM2
        run: |
          /home/ubuntu/.nvm/versions/node/v22.22.2/bin/pm2 delete Frontend || true
          cd frontend
          /home/ubuntu/.nvm/versions/node/v22.22.2/bin/pm2 serve build 3000 --name Frontend --spa
          /home/ubuntu/.nvm/versions/node/v22.22.2/bin/pm2 status
          /home/ubuntu/.nvm/versions/node/v22.22.2/bin/pm2 save